[project]
name = "wbparser"
version = "0.1.0"
description = "Парсер данных с Wildberries"
authors = [
    {name = "Anna_Putilovskaya",email = "putilovakayaa@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "seleniumbase (>=4.48.2,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
